#!/bin/bash

# Generate environment files
/home/ec2-user/projects/styx/scripts/generate_env.sh

# Source the generated .env file to ensure all environment variables are available
if [ -f /home/ec2-user/projects/styx/.env ]; then
  export $(cat /home/ec2-user/projects/styx/.env | grep -v '^#' | xargs)
  echo "Loaded environment variables from .env file"
else
  echo "Environment file .env does not exist"
  exit 1
fi

# Generate the Nginx Dockerfile
/home/ec2-user/projects/styx/scripts/generate_dockerfile.sh

# Generate JSON files with replaced placeholders for the current environment
/home/ec2-user/projects/styx/scripts/generate_json.sh
