# Use a base image with Python and necessary tools
FROM python:3.10-slim

WORKDIR /app

COPY ./styx_packages /app/styx_packages
RUN pip install ./styx_packages

# Install necessary libraries
RUN apt-get update && apt-get install -y sshpass openssh-client autossh curl && \
    pip install requests psycopg2-binary SQLAlchemy

# Copy the script and database utilities to the container
COPY AWS/ecs/raw_data_transfer_task/raw_data_transfer_test.py /app/raw_data_transfer_test.py

# Create directory for SSH keys
RUN mkdir /root/.ssh/

# Run the application
ENTRYPOINT ["python", "/app/raw_data_transfer_test.py"]