FROM flyway/flyway:10.13

# Install gettext for envsubst
USER root
RUN apt-get update && apt-get install -y gettext-base

# Create a new user for running the scripts
RUN useradd -m flywayuser

# Create the directory and set proper permissions
RUN mkdir -p /flyway/sql && chown -R flywayuser:flywayuser /flyway/sql
RUN mkdir -p /flyway/conf && chown -R flywayuser:flywayuser /flyway/conf

# Switch to the new user
USER flywayuser

# Copy the .env file, Flyway configuration, and entrypoint script
COPY --chown=flywayuser:flywayuser test/entrypoint.sh /flyway/entrypoint.sh
COPY --chown=flywayuser:flywayuser test/sql /flyway/sql
COPY --chown=flywayuser:flywayuser test/flyway.conf.template /flyway/conf/flyway.conf.template
COPY --chown=flywayuser:flywayuser .env /flyway/.env

# Set the correct permissions for the entrypoint script and configuration directory
RUN chmod +x /flyway/entrypoint.sh
RUN chmod -R 755 /flyway/conf

# Set the entrypoint
ENTRYPOINT ["/flyway/entrypoint.sh"]