# Use an official Python runtime as a base image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /mlflow

# Install MLflow and necessary libraries
RUN pip install "mlflow[extras]==2.12.1" psycopg2-binary boto3==1.34.93

# Expose the port MLflow will run on
EXPOSE 5000

CMD mlflow server \
    --backend-store-uri $MLFLOW_BACKEND_URI \
    --default-artifact-root $MLFLOW_ARTIFACT_ROOT \
    --host 0.0.0.0
