version: '3.8'

services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_PASS: ${DB_PASS}
    volumes:
      - db-data:/var/lib/postgresql/data
      # - ./init_db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraping
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      SCRAPER_URL: ${SCRAPER_URL}
    volumes:
      - ./logs:/var/log
    depends_on:
      db:
        condition: service_healthy
    # command: ["/bin/bash", "-c", "/usr/local/bin/wait-for-it.sh db:5432 -- python /app/src/data/load_new_data.py 'https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGx6TVdZU0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US%3Aen'"]

volumes:
  db-data: