version: '3.8'

services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_PASS: ${DB_PASS}
    volumes:
      - db-data:/var/lib/postgresql/data
      # - ./init_db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraping
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      SCRAPER_URL: ${SCRAPER_URL}
    volumes:
      - ./logs:/var/log
    depends_on:
      db:
        condition: service_healthy
    # command: ["/bin/bash", "-c", "/usr/local/bin/wait-for-it.sh db:5432 -- python /app/src/data/load_new_data.py 'https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGx6TVdZU0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US%3Aen'"]
  
  airflow-webserver:
    image: apache/airflow:2.7.3-python3.10
    user: "airflow"
    group_add:
      - 999  # Docker group ID
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASS}@db/${POSTGRES_DB}
      - AIRFLOW__CORE__FERNET_KEY=${FERNET_KEY}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW_UID=${AIRFLOW_UID}
      - AIRFLOW_GID=${AIRFLOW_GID}
      - AIRFLOW_USER=${AIRFLOW_USER}
      - AIRFLOW_FIRST_NAME=${AIRFLOW_FIRST_NAME}
      - AIRFLOW_LAST_NAME=${AIRFLOW_LAST_NAME}
      - AIRFLOW_ROLE=${AIRFLOW_ROLE}
      - AIRFLOW_EMAIL=${AIRFLOW_EMAIL}
      - AIRFLOW_PASS=${AIRFLOW_PASS}
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dags:/opt/airflow/dags
      - ./logs/airflow:/opt/airflow/logs
      - ./airflow-entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]
    command: ["webserver"]
    depends_on:
      - db 

  airflow-scheduler:
    image: apache/airflow:2.7.3-python3.10
    user: "airflow"
    group_add:
      - 999  # Docker group ID
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASS}@db/${POSTGRES_DB}
      - AIRFLOW__CORE__FERNET_KEY=${FERNET_KEY}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW_UID=${AIRFLOW_UID}
      - AIRFLOW_GID=${AIRFLOW_GID}
      - AIRFLOW_USER=${AIRFLOW_USER}
      - AIRFLOW_FIRST_NAME=${AIRFLOW_FIRST_NAME}
      - AIRFLOW_LAST_NAME=${AIRFLOW_LAST_NAME}
      - AIRFLOW_ROLE=${AIRFLOW_ROLE}
      - AIRFLOW_EMAIL=${AIRFLOW_EMAIL}
      - AIRFLOW_PASS=${AIRFLOW_PASS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dags:/opt/airflow/dags
      - ./logs/airflow:/opt/airflow/logs
      - ./airflow-entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]
    command: ["scheduler"]
    depends_on:
      - db

volumes:
  db-data:


# - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASS}@db/${POSTGRES_DB}
