version: '3.8'
services:
  db_prod:
    build: 
      context: .
      dockerfile: ./dockerfiles/Dockerfile.db_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    volumes:
      - db-data-prod:/var/lib/postgresql/data
    ports:
      - "${DB_PORT_OUTER}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  flyway_prod:
    build: 
      context: .
      dockerfile: ./dockerfiles/Dockerfile.flyway
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT_INNER}
    depends_on:
      db_prod:
        condition: service_healthy

  redis_prod:
    image: redis:7.2.4
    ports:
      - "${REDIS_PORT_OUTER}:6379"
    volumes:
      - redis-data-prod:/data
    environment:
      REDIS_PASS: ${REDIS_PASS}
    command: ["redis-server", "--requirepass", "${REDIS_PASS}", "--appendonly", "yes"]

  inference_api_prod:
    build:
        context:  .
        dockerfile: ./dockerfiles/Dockerfile.model_inference_api
    image: inference_api_prod_img
    environment:
      REL_API_URL: ${REL_API_URL}
    ports:
      - "8001:8001"
    volumes:
      - ./logs_prod/:/var/log/
    depends_on:
      - rel

  data_provider_api_prod:
    build:
        context: .
        dockerfile: ./dockerfiles/Dockerfile.data_provider_api
    image: data_provider_api_prod_img
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT_INNER}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT_INNER}
      REDIS_PASS: ${REDIS_PASS}
    ports:
      - "8003:8003"
    volumes:
      - ./logs_prod/:/var/log/
    depends_on:
      db_prod:
        condition: service_healthy
      redis_prod:
        condition: service_started

  frontend_prod:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.frontend
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - data_provider_api_prod
  
  scraper_prod:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.scraper_service
    image: styx_scraper_img
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      SCRAPER_URL: ${SCRAPER_URL}
    volumes:
      - ./logs_prod/:/var/log
    depends_on:
      db_prod:
        condition: service_healthy

volumes:
  db-data-prod:
  redis-data-prod:
  # react-build-test: