FROM quay.io/jupyter/pytorch-notebook:python-3.11

USER root

COPY requirements/requirements_jupyter.txt /requirements/

RUN pip install --no-cache-dir -r /requirements/requirements_jupyter.txt

USER jovyan
