[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
[tool.flake8]
max-line-length = 88
max-complexity = 12
select = ["C", "E", "F", "W", "B", "B950"]
ignore = ["E203", "W503"]
