# Use the Python 3.10 slim image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

COPY ./data_provider_api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install pytest==7.4.4
RUN pip install httpx
RUN pip install psycopg2-binary

COPY ./data_provider_api/app ./app/
COPY ./logging_config.py ./app/

# # Install tree (if not already installed)
# RUN apt-get update && apt-get install -y tree

# # Run tree command to print directory tree on container start
# CMD ["tree", "."]

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8003"]
