# Use the Python 3.10 slim image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

COPY ./styx_packages /app/styx_packages
RUN pip install ./styx_packages

COPY ./requirements/requirements_data_provider_api.txt .
RUN pip install --no-cache-dir -r requirements_data_provider_api.txt

COPY ./styx_app/data_provider_api/app ./app/

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0"]

