FROM nginx:1.24.0

COPY ./styx_app/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./styx_app/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY .htpasswd /etc/nginx/.htpasswd

COPY --from=styx_frontend_{{ENV}}:latest /app/build /usr/share/nginx/html/{{ENV}}

EXPOSE 80
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]
