FROM python:3.10-slim

WORKDIR /mlflow

RUN pip install "mlflow[extras]==2.12.1" psycopg2-binary boto3==1.34.51

EXPOSE 5000

CMD mlflow server \
    --backend-store-uri $MLFLOW_BACKEND_URI \
    --default-artifact-root $MLFLOW_ARTIFACT_ROOT \
    --host 0.0.0.0
